# Generated by Django 5.1.1 on 2024-09-25 17:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=0, verbose_name="Количество"),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="Ключ сессии"
                    ),
                ),
                (
                    "created_timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "product_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.productvariant",
                        verbose_name="Вариант продукта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Корзину",
                "verbose_name_plural": "Корзины",
                "db_table": "cart",
            },
        ),
    ]
